spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: false   # en prod, la base doit déjà être gérée par Flyway depuis le début

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}   # pas de valeur par défaut en prod, doit être explicite

logging:
  level:
    root: WARN
    tn.gov.dgi.immatriculation: INFO
    org.hibernate.SQL: WARN

management:
  endpoint:
    health:
      show-details: never