apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dgi
type: Opaque
stringData:
  POSTGRES_DB: dgi_immatriculation
  POSTGRES_USER: dgi_user
  POSTGRES_PASSWORD: changeme
  DB_URL: jdbc:postgresql://postgres-service:5432/dgi_immatriculation
